### ISSUE TITLE
Error while trying to train

### ISSUE THREAD

**Issue by lkbr1808** [microsoft/DIF-Net#3]
Hello,

I am getting an issue when running `python train.py --config=configs/train/table.yml`
The error occuring is
```
Traceback (most recent call last):
  File "/home/lkbr/anaconda3/envs/dif/lib/python3.6/site-packages/scipy/io/matlab/mio.py", line 39, in _open_file
    return open(file_like, mode), True
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/table/surface_pts_n_normal/1011e1c9812b84d2a9ed7bb5b55809f8.mat'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 71, in <module>
    sdf_dataset = dataset.PointCloudMulti(root_dir=data_path, max_num_instances=meta_params['num_instances'],**meta_params)
  File "/home/lkbr/repos/DIF-Net/dataset.py", line 111, in __init__
    on_surface_points=on_surface_points,expand=expand,max_points=max_points) for idx, dir in enumerate(self.instance_dirs)]
  File "/home/lkbr/repos/DIF-Net/dataset.py", line 111, in <listcomp>
    on_surface_points=on_surface_points,expand=expand,max_points=max_points) for idx, dir in enumerate(self.instance_dirs)]
  File "/home/lkbr/repos/DIF-Net/dataset.py", line 23, in __init__
    point_cloud = loadmat(pointcloud_path)
  File "/home/lkbr/anaconda3/envs/dif/lib/python3.6/site-packages/scipy/io/matlab/mio.py", line 216, in loadmat
    with _open_file_context(file_name, appendmat) as f:
  File "/home/lkbr/anaconda3/envs/dif/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/lkbr/anaconda3/envs/dif/lib/python3.6/site-packages/scipy/io/matlab/mio.py", line 19, in _open_file_context
    f, opened = _open_file(file_like, appendmat, mode)
  File "/home/lkbr/anaconda3/envs/dif/lib/python3.6/site-packages/scipy/io/matlab/mio.py", line 45, in _open_file
    return open(file_like, mode), True
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/table/surface_pts_n_normal/1011e1c9812b84d2a9ed7bb5b55809f8.mat'
```
Which seems to be at the very first .mat file. The error occurs when trying to train any of the datasets provided by you.
My system is Xubuntu with a GTX 1080 and Intel CPU. Let me know if you need any other system information.

**Comment by YuDeng** [comment]
Hi, this repo does not contain the processed training data. The training data is too large (around 400GB) to share. Alternatively, we provide test data (100 subjects for each category). You may first download them using the link provided in the readme and run the training code with the test data to check if it works. 

Currently, to generate the training set for our method, you can refer to [mesh_to_sdf](https://github.com/marian42/mesh_to_sdf), which we also used for our data process. Let me know if you have any problem with it.
